# -*- coding: utf-8 -*-
"""1week_AI2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i2UFKRDcY6eiNjUKUVGCRwO9EQsaP8VG
"""

#1
num_list=[1,5,7,15,16,22,28,29]
result=[]
def get_odd_num(num_list):
  for i in num_list:
    if i % 2 == 1:
     result.append(i)
  return result
print(get_odd_num(num_list))

#2
sentence = "way a is there will a is there where"
def reverse_sentence(sentence):
    sentence=str(sentence)
    split_sentence = sentence.split(' ')
    reverse_sentence=reversed(split_sentence)
    final_str = ' '.join(reverse_sentence)
    return final_str
print(reverse_sentence(sentence))

#3
score=[(100,100),(95,90),(55,60),(75,80),(70,70)]
def get_avg(score):
  for i in range(0,5):
    score[i]
    avg=(score[i])/2
    print(avg)
print(get_avg(score))

#4
dict_first={'사과':30,'배':15,'감':10,'포도':10}
dict_second={'사과':5,'감':25,'배':15,'귤':25}
def merge_dict(dict_first, dict_second):
  for key in dict_first:
    if key in dict_second:
      dict_first[key]+=dict_second[key]
  return dict_first
print(merge_dict(dict_first,dict_second))



inputs="cat32dog16cow5"
print(type(inputs))
list=[]

def find_string(inputs):
    list+=inputs.split(int)
    print(list)

string_list=find_string(inputs)
print(string_list)
